### PR TITLE
melee crate article

### PR DESCRIPTION
**Pull request by brianzjk**
this is how you add an article right

### CODE REVIEW

**Comment by kenos1** [comment]
Aegis, Flint, Regular, and Melee crate share the same article

**Comment by kenos1** [comment]
you could use an html element in the crates article like

```html
<h2 id="melee-crate">Melee Crate</h2>
```

and then link it elsewhere (i forgot the link for crate article)

```md
[Melee Crate](/obstacles/crate#melee-crate)
```

**Comment by 1092384** [comment]
We don't need a melee crate article, it has enough information in the article for crates

https://github.com/HasangerGames/suroi-wiki/blob/main/app/(wiki)/(articles)/obstacles/articles/crates.mdx

**Comment by 1092384** [comment]
@brianzjk There's no need to make seperate articles for the crate variants because they are too similar.

If you want to add more information go to https://github.com/HasangerGames/suroi-wiki/blob/main/app/(wiki)/(articles)/obstacles/articles/crates.mdx and resubmit your changes to that file

**Comment by brianzjk** [comment]
got it -- will do later!

**Pull request closed without merging**
