### PR TITLE
Updated MG36 Article

### PR DESCRIPTION
**Pull request by BearHey**
I removed the periods and added a new trivia fact

### CODE REVIEW

**Comment by BearHey** [comment]
I'm still getting emails about this lol.

**Comment by itsNMD404** [comment]
> I'm still getting emails about this lol.
lmaoooo

**Comment by BearHey** [comment]
What ever happened to me being a waste of your time?  If you are going to snipe at me in git hub why did you block me on discord?  Make up your mind, buddy, try getting a job while you're at it, you seem to have a bit too much time on your hands.

**Comment by BearHey** [comment]
Alright, unsubscribed, if you want to bash me do it on Discord, or just baby rage and call me names on your private channels.  What I don't know can't hurt me

**Comment by 1092384** [comment]
Whatever happened to not caring about suroi anymore

**Pull request merged**
