### PR TITLE
super barrel article and menu button

### PR DESCRIPTION
**Pull request by CroissantEdit**

### CODE REVIEW

**Comment by CroissantEdit** [comment]
do not look at what i did i do not know

**Comment by Compositr** [comment]
denied

**Comment by CroissantEdit** [comment]
WHY

**Comment by Compositr** [comment]
(kidding i havent even read the code)

**Comment by CroissantEdit** [comment]
😭

**Comment by CroissantEdit** [comment]
frike u, u give me herat attack

**Comment by kenos1** [comment]
Answer my code reviews

- joe

**Review by Compositr — APPROVED** [review]
begrudgingly

**Pull request merged**
