### PR TITLE
Added Dropdown component and used dropdowns for each weapons grid

### PR DESCRIPTION
**Pull request by pythoncat1**

### CODE REVIEW

**Comment by kenos1** [comment]
Not sure, but I think we use a dropdown component? Ask @Compositr lol

**Comment by kenos1** [comment]
Also, use the tailwindcss classes lmao

**Comment by kenos1** [comment]
Merging, but adding changing that will be made

**Comment by pythoncat1** [comment]
Sorry I forgot about tailwind

**Pull request merged**
