### PR TITLE
Create tactical_pack.md

### PR DESCRIPTION
**Pull request by sawq375**
final gear text omg

### CODE REVIEW

**Comment by kenos1** [comment]
btw what's your discord? We award people for writing articles with a special role on the discord server.

**Comment by 1092384** [comment]
Also, please try to merge your changes into one pull request instead of making one for every change. If you need help with this, contact on discord.

**Comment by kenos1** [comment]
It's probably because of edit button in wiki

**Comment by 1092384** [comment]
@kenos1 I'm guessing this guy edits directly in github?

**Comment by kenos1** [comment]
Yeah

**Comment by sawq375** [comment]
hm?

**Comment by sawq375** [comment]
srry my bad also im not in the suroi discord my school blocks it ☠️

**Pull request merged**
