### PR TITLE
Add Chpter Website. Rename developer roles.

### PR DESCRIPTION
**Pull request by ChpssCode**
Lol I did this on mobile cus I have nothing to do for 5 hours.

### CODE REVIEW

**Comment by kenos1** [comment]
I don't really like the new developer role names, but I will merge your website link in

**Comment by 1092384** [comment]
^ this

**Comment by kenos1** [comment]
https://github.com/HasangerGames/suroi-wiki/commit/54d7c7e4c8e0a0b6d48b560290c02fc6e44c0792 done

**Comment by 1092384** [comment]
So chp is bored

Go write some articles. chp

**Pull request closed without merging**
