### PR TITLE
barrel article and some fixes

### PR DESCRIPTION
**Pull request by CroissantEdit**
cool

### CODE REVIEW

**Review by Compositr — CHANGES_REQUESTED** [review]
Still missing some capitals as requested by Amyklae

**Comment by CroissantEdit** [comment]
I'm having a stroke read that

**Comment by Compositr** [comment]
I fixed my spelling :P

**Comment by CroissantEdit** [comment]
can someone translate it for me

**Review by Compositr — CHANGES_REQUESTED** [review]
Warehouse and Port are still not capitalised

**Review by Compositr — APPROVED** [review]
good enough

**Pull request merged**
